
desc "Hello"
lane :hello do
  puts 'Hello, dude!'
end

lane :discord_send_message do

webhook_url = ENV['DISCORD_WEBHOOK_URL']

  discord_notifier(
    webhook_url:webhook_url,
    title: "CI Notification",
    description: "Success build and test",  
  )
end

lane :build_for_testing do
  scan(
    #scheme: 'Debug',
    build_for_testing: true
  )
end

lane :testing do 
  run_tests(
    test_without_building: true
  )
end

lane :build_and_test do
  build_for_testing
  testing
  discord_send_message
  puts 'SUCCESS BUILD AND TEST'
end